var hierarchy =
[
    [ "ActivityBar::ActivityItem", "structActivityBar_1_1ActivityItem.html", null ],
    [ "AstIRBuilder::BlockScope", "structAstIRBuilder_1_1BlockScope.html", null ],
    [ "AstIRBuilder::BlockScope::ShadowedVar", "structAstIRBuilder_1_1BlockScope_1_1ShadowedVar.html", null ],
    [ "AstIRBuilder::FunctionEmitCtx", "structAstIRBuilder_1_1FunctionEmitCtx.html", null ],
    [ "AstIRBuilder::LoopContext", "structAstIRBuilder_1_1LoopContext.html", null ],
    [ "AstIRBuilder::PendingRegPrecompiledModule", "structAstIRBuilder_1_1PendingRegPrecompiledModule.html", null ],
    [ "AstIRBuilder::TryEmitCtx", "structAstIRBuilder_1_1TryEmitCtx.html", null ],
    [ "AstIRBuilder::TryFinallyContext", "structAstIRBuilder_1_1TryFinallyContext.html", null ],
    [ "AstIRBuilder::UpvalueInfo", "structAstIRBuilder_1_1UpvalueInfo.html", null ],
    [ "AstIRBuilder::VarInfo", "structAstIRBuilder_1_1VarInfo.html", null ],
    [ "AstNodeInfo", "structAstNodeInfo.html", null ],
    [ "AstToyLevel", "structAstToyLevel.html", null ],
    [ "AstToyLevel::TreeNode", "structAstToyLevel_1_1TreeNode.html", null ],
    [ "AstToyLibrary", "classAstToyLibrary.html", null ],
    [ "AstViewer::CollapseKeyHash", "structAstViewer_1_1CollapseKeyHash.html", null ],
    [ "AstViewer::RtNode", "structAstViewer_1_1RtNode.html", null ],
    [ "AstVisualizerLibrary", "classAstVisualizerLibrary.html", null ],
    [ "BackendComparePanel::BackendResult", "structBackendComparePanel_1_1BackendResult.html", null ],
    [ "BackendExecResult", "structBackendExecResult.html", [
      [ "BackendExecDetail", "structBackendExecDetail.html", null ]
    ] ],
    [ "BackendExecutionService", "classBackendExecutionService.html", null ],
    [ "BackendParallelPanel::BackendExecResult", "structBackendParallelPanel_1_1BackendExecResult.html", null ],
    [ "BackendParallelSample", "structBackendParallelSample.html", null ],
    [ "BackendPerfResult", "structBackendPerfResult.html", null ],
    [ "BreakpointConditionLibrary", "classBreakpointConditionLibrary.html", null ],
    [ "BreakpointInfo", "structBreakpointInfo.html", null ],
    [ "BreakpointScenario", "structBreakpointScenario.html", null ],
    [ "BugHuntItem", "structBugHuntItem.html", null ],
    [ "BugHuntLibrary", "classBugHuntLibrary.html", null ],
    [ "BugHuntVariant", "structBugHuntVariant.html", null ],
    [ "BugHuntVariantLibrary", "classBugHuntVariantLibrary.html", null ],
    [ "BuiltinMethodResult", "structBuiltinMethodResult.html", null ],
    [ "BuiltinMethods", "classBuiltinMethods.html", null ],
    [ "BuiltinModuleRegistry", "classBuiltinModuleRegistry.html", null ],
    [ "BytecodeCache", "classBytecodeCache.html", null ],
    [ "BytecodeCache::CacheKey", "structBytecodeCache_1_1CacheKey.html", null ],
    [ "BytecodeCache::MemoEntry", "structBytecodeCache_1_1MemoEntry.html", null ],
    [ "BytecodeChunk", "structBytecodeChunk.html", null ],
    [ "BytecodeChunk::SlotNameRange", "structBytecodeChunk_1_1SlotNameRange.html", null ],
    [ "BytecodeChunk::VarCacheEntry", "structBytecodeChunk_1_1VarCacheEntry.html", null ],
    [ "BytecodeIRBackend::PendingJump", "structBytecodeIRBackend_1_1PendingJump.html", null ],
    [ "BytecodeIRBackend::StackEffect", "structBytecodeIRBackend_1_1StackEffect.html", null ],
    [ "BytecodeTraceLibrary", "classBytecodeTraceLibrary.html", null ],
    [ "BytecodeTracePanel::TraceEntry", "structBytecodeTracePanel_1_1TraceEntry.html", null ],
    [ "CallFrame", "structCallFrame.html", null ],
    [ "CallStackEntry", "structCallStackEntry.html", null ],
    [ "CallStackLibrary", "classCallStackLibrary.html", null ],
    [ "CallStackScenario", "structCallStackScenario.html", null ],
    [ "CFGNode", "structCFGNode.html", null ],
    [ "ClassInfo", "structClassInfo.html", null ],
    [ "ClosureInspectorLibrary", "classClosureInspectorLibrary.html", null ],
    [ "ClosureScenario", "structClosureScenario.html", null ],
    [ "CodeEditor::ErrorRange", "structCodeEditor_1_1ErrorRange.html", null ],
    [ "CodeSnippet", "structCodeSnippet.html", null ],
    [ "CodeSnippetEngine", "classCodeSnippetEngine.html", null ],
    [ "CodeSnippetEngine::Expansion", "structCodeSnippetEngine_1_1Expansion.html", null ],
    [ "Compiler::CatchVarBindInfo", "structCompiler_1_1CatchVarBindInfo.html", null ],
    [ "Compiler::CompileContext", "structCompiler_1_1CompileContext.html", null ],
    [ "Compiler::CompileContextGuard", "structCompiler_1_1CompileContextGuard.html", null ],
    [ "Compiler::LoopContext", "structCompiler_1_1LoopContext.html", null ],
    [ "Compiler::TryCatchPatchInfo", "structCompiler_1_1TryCatchPatchInfo.html", null ],
    [ "Compiler::TryFinallyContext", "structCompiler_1_1TryFinallyContext.html", null ],
    [ "CompileResult", "structCompileResult.html", null ],
    [ "CoroutineSample", "structCoroutineSample.html", null ],
    [ "CoroutineVisualizerPanel::BackendExecResult", "structCoroutineVisualizerPanel_1_1BackendExecResult.html", null ],
    [ "Course", "structCourse.html", null ],
    [ "CourseChapter", "structCourseChapter.html", null ],
    [ "CourseLesson", "structCourseLesson.html", null ],
    [ "CourseSystemLibrary", "classCourseSystemLibrary.html", null ],
    [ "CowProcessInfo", "structCowProcessInfo.html", null ],
    [ "DebugEvaluator", "classDebugEvaluator.html", null ],
    [ "Diagnostic", "structDiagnostic.html", null ],
    [ "DiagnosticBag", "classDiagnosticBag.html", null ],
    [ "DominanceFrontier", "classDominanceFrontier.html", null ],
    [ "DominatorTree", "classDominatorTree.html", null ],
    [ "EnumInfo", "structEnumInfo.html", null ],
    [ "EnumVariant", "structEnumVariant.html", null ],
    [ "Environment::ClosureCapture", "structEnvironment_1_1ClosureCapture.html", null ],
    [ "ErrorHintEngine", "classErrorHintEngine.html", null ],
    [ "ErrorHintEngine::ErrorPattern", "structErrorHintEngine_1_1ErrorPattern.html", null ],
    [ "ErrorInfo", "structErrorInfo.html", null ],
    [ "EscapeAnalysisLibrary", "classEscapeAnalysisLibrary.html", null ],
    [ "EscapeScenario", "structEscapeScenario.html", null ],
    [ "EscapeSimObject", "structEscapeSimObject.html", null ],
    [ "EscapeStateInfo", "structEscapeStateInfo.html", null ],
    [ "ExceptionBreakpointState", "structExceptionBreakpointState.html", null ],
    [ "ExceptionFlowLibrary", "classExceptionFlowLibrary.html", null ],
    [ "ExceptionPhaseDoc", "structExceptionPhaseDoc.html", null ],
    [ "ExceptionPhaseLibrary", "classExceptionPhaseLibrary.html", null ],
    [ "ExceptionScenario", "structExceptionScenario.html", null ],
    [ "ExecutionTraceRecorder", "classExecutionTraceRecorder.html", null ],
    [ "Exercise", "structExercise.html", null ],
    [ "ExerciseGraderLibrary", "classExerciseGraderLibrary.html", null ],
    [ "ExerciseGraderPanel::ExecResult", "structExerciseGraderPanel_1_1ExecResult.html", null ],
    [ "FormatOptions", "structFormatOptions.html", null ],
    [ "FunctionBreakpointInfo", "structFunctionBreakpointInfo.html", null ],
    [ "FuzzSample", "structFuzzSample.html", null ],
    [ "GcContainerTypeRow", "structGcContainerTypeRow.html", null ],
    [ "GcManager", "classGcManager.html", null ],
    [ "GcManager::CallbackSuppressor", "classGcManager_1_1CallbackSuppressor.html", null ],
    [ "GcModeRow", "structGcModeRow.html", null ],
    [ "GcPhaseInfo", "structGcPhaseInfo.html", null ],
    [ "GcPhaseRow", "structGcPhaseRow.html", null ],
    [ "GcScenarioInfo", "structGcScenarioInfo.html", null ],
    [ "GcSimResult", "structGcSimResult.html", null ],
    [ "GcSimStep", "structGcSimStep.html", null ],
    [ "GcStatsSnapshot", "structGcStatsSnapshot.html", null ],
    [ "GcVisualizerLibrary", "classGcVisualizerLibrary.html", null ],
    [ "GeneratorChunkInfo", "structGeneratorChunkInfo.html", null ],
    [ "GlobalSlotAllocator", "classGlobalSlotAllocator.html", null ],
    [ "GlossaryPanel::TermEntry", "structGlossaryPanel_1_1TermEntry.html", null ],
    [ "GradeItem", "structGradeItem.html", null ],
    [ "GuidedTour::Step", "structGuidedTour_1_1Step.html", null ],
    [ "HeapObjectSnapshot", "structHeapObjectSnapshot.html", null ],
    [ "HighlightRule", "structHighlightRule.html", null ],
    [ "HotspotScenario", "structHotspotScenario.html", null ],
    [ "IBackend", "classIBackend.html", [
      [ "IVmBackend", "classIVmBackend.html", [
        [ "RegisterVM", "classRegisterVM.html", null ],
        [ "VM", "classVM.html", null ]
      ] ],
      [ "Interpreter", "classInterpreter.html", null ]
    ] ],
    [ "IcSimStep", "structIcSimStep.html", null ],
    [ "IcStateInfo", "structIcStateInfo.html", null ],
    [ "Ide::ChunkRowInfo", "structIde_1_1ChunkRowInfo.html", null ],
    [ "Ide::EditorTabData", "structIde_1_1EditorTabData.html", null ],
    [ "Ide::FluentPalette", "structIde_1_1FluentPalette.html", null ],
    [ "IDebugController", "classIDebugController.html", [
      [ "DebugController", "classDebugController.html", null ],
      [ "VmStepper", "classVmStepper.html", null ]
    ] ],
    [ "IdeController::VmStateChangedListener", "structIdeController_1_1VmStateChangedListener.html", null ],
    [ "IdeController::WatchResult", "structIdeController_1_1WatchResult.html", null ],
    [ "InlineCacheLibrary", "classInlineCacheLibrary.html", null ],
    [ "Interpreter::CallFrameGuard", "structInterpreter_1_1CallFrameGuard.html", null ],
    [ "Interpreter::ChainInfo", "structInterpreter_1_1ChainInfo.html", null ],
    [ "Interpreter::EnvSnapshot", "structInterpreter_1_1EnvSnapshot.html", null ],
    [ "Interpreter::InstSnapEntry", "structInterpreter_1_1InstSnapEntry.html", null ],
    [ "Interpreter::RecursionGuard", "structInterpreter_1_1RecursionGuard.html", null ],
    [ "Interpreter::ReplState", "structInterpreter_1_1ReplState.html", null ],
    [ "Interpreter::StateSnapshot", "structInterpreter_1_1StateSnapshot.html", null ],
    [ "Interpreter::TcoScopeGuard", "structInterpreter_1_1TcoScopeGuard.html", null ],
    [ "IRBackend", "classIRBackend.html", [
      [ "BytecodeIRBackend", "classBytecodeIRBackend.html", null ],
      [ "RegisterBytecodeBackend", "classRegisterBytecodeBackend.html", null ]
    ] ],
    [ "IRBasicBlock", "structIRBasicBlock.html", null ],
    [ "IRBuilder", "classIRBuilder.html", [
      [ "AstIRBuilder", "classAstIRBuilder.html", null ]
    ] ],
    [ "IRCFG", "classIRCFG.html", null ],
    [ "IRFunction", "structIRFunction.html", null ],
    [ "IRFunction::SlotNameRange", "structIRFunction_1_1SlotNameRange.html", null ],
    [ "IRInstruction", "structIRInstruction.html", null ],
    [ "IRLoweringExample", "structIRLoweringExample.html", null ],
    [ "IRModule", "structIRModule.html", null ],
    [ "IROperand", "structIROperand.html", null ],
    [ "IROperandList", "classIROperandList.html", null ],
    [ "IROptimizationExample", "structIROptimizationExample.html", null ],
    [ "IROptReplayLibrary", "classIROptReplayLibrary.html", null ],
    [ "IROptStepRecord", "structIROptStepRecord.html", null ],
    [ "IRTransformLibrary", "classIRTransformLibrary.html", null ],
    [ "JitContextField", "structJitContextField.html", null ],
    [ "JitOpCodeCategory", "structJitOpCodeCategory.html", null ],
    [ "JitRegisterInfo", "structJitRegisterInfo.html", null ],
    [ "JitRunner::AsmDumpResult", "structJitRunner_1_1AsmDumpResult.html", null ],
    [ "JitRunner::HotspotResult", "structJitRunner_1_1HotspotResult.html", null ],
    [ "JitRunner::HotspotRow", "structJitRunner_1_1HotspotRow.html", null ],
    [ "JitRunner::TierMetricsResult", "structJitRunner_1_1TierMetricsResult.html", null ],
    [ "JitRunner::TierMetricsRow", "structJitRunner_1_1TierMetricsRow.html", null ],
    [ "JitRunner::TypeFeedbackResult", "structJitRunner_1_1TypeFeedbackResult.html", null ],
    [ "JitRunner::TypeFeedbackRow", "structJitRunner_1_1TypeFeedbackRow.html", null ],
    [ "JitVisualizerLibrary", "classJitVisualizerLibrary.html", null ],
    [ "LabChapter", "structLabChapter.html", null ],
    [ "LabExercise", "structLabExercise.html", null ],
    [ "LabManualContent", "classLabManualContent.html", null ],
    [ "LearnerProgress", "structLearnerProgress.html", null ],
    [ "LearnerProgressStore", "classLearnerProgressStore.html", null ],
    [ "LearningActivity", "structLearningActivity.html", null ],
    [ "LearningPathData", "classLearningPathData.html", null ],
    [ "Lexer", "classLexer.html", null ],
    [ "LintRuleInfo", "structLintRuleInfo.html", null ],
    [ "LintRuleLibrary", "classLintRuleLibrary.html", null ],
    [ "LintSample", "structLintSample.html", null ],
    [ "LintSampleLibrary", "classLintSampleLibrary.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "LoopUnrollingLibrary", "classLoopUnrollingLibrary.html", null ],
    [ "MagicCommand", "structMagicCommand.html", null ],
    [ "MagicCommands", "classMagicCommands.html", null ],
    [ "MarkdownRenderer::HeadingEntry", "structMarkdownRenderer_1_1HeadingEntry.html", null ],
    [ "MatchCase", "structMatchCase.html", null ],
    [ "MemoryAnimLibrary", "classMemoryAnimLibrary.html", null ],
    [ "MemoryAnimPhase", "structMemoryAnimPhase.html", null ],
    [ "MemoryInspectionAPI", "classMemoryInspectionAPI.html", null ],
    [ "MemoryLayoutLibrary", "classMemoryLayoutLibrary.html", null ],
    [ "MemoryModelLibrary", "classMemoryModelLibrary.html", null ],
    [ "MemoryScenario", "structMemoryScenario.html", null ],
    [ "MemorySimField", "structMemorySimField.html", null ],
    [ "minilang::CrashHandler", "classminilang_1_1CrashHandler.html", null ],
    [ "minilang::CrashReport", "structminilang_1_1CrashReport.html", null ],
    [ "minilang::HostFunctionRegistry", "classminilang_1_1HostFunctionRegistry.html", null ],
    [ "minilang::HostFunctionRegistry::Entry", "structminilang_1_1HostFunctionRegistry_1_1Entry.html", null ],
    [ "minilang::HostValue", "structminilang_1_1HostValue.html", null ],
    [ "minilang::TypeChecker", "classminilang_1_1TypeChecker.html", [
      [ "minilang::MiniLangTypeChecker", "classminilang_1_1MiniLangTypeChecker.html", null ]
    ] ],
    [ "minilang::TypeInfo", "structminilang_1_1TypeInfo.html", null ],
    [ "MiniLangEscapeMapping", "structMiniLangEscapeMapping.html", null ],
    [ "MiniLangIcMapping", "structMiniLangIcMapping.html", null ],
    [ "MiniLangRegModel", "structMiniLangRegModel.html", null ],
    [ "MiniLangUnrollMapping", "structMiniLangUnrollMapping.html", null ],
    [ "ModuleConceptRow", "structModuleConceptRow.html", null ],
    [ "ModuleScenarioInfo", "structModuleScenarioInfo.html", null ],
    [ "ModuleSimResult", "structModuleSimResult.html", null ],
    [ "ModuleSimStep", "structModuleSimStep.html", null ],
    [ "ModuleSystemLibrary", "classModuleSystemLibrary.html", null ],
    [ "ModuleTopLevelRenamer", "classModuleTopLevelRenamer.html", null ],
    [ "NaNBoundingBox", "structNaNBoundingBox.html", null ],
    [ "NaNBox", "classNaNBox.html", null ],
    [ "NaNBoxingTypeInfo", "structNaNBoxingTypeInfo.html", null ],
    [ "NaNBoxSnapshot", "structNaNBoxSnapshot.html", null ],
    [ "NaturalLoopInfo", "classNaturalLoopInfo.html", null ],
    [ "NaturalLoopInfo::Loop", "structNaturalLoopInfo_1_1Loop.html", null ],
    [ "NumericOps::ArithResult", "structNumericOps_1_1ArithResult.html", null ],
    [ "NumericOps::CompareResult", "structNumericOps_1_1CompareResult.html", null ],
    [ "OpCodeDocEntry", "structOpCodeDocEntry.html", null ],
    [ "OpCodeInfo", "structOpCodeInfo.html", null ],
    [ "OpCodePerfDoc", "structOpCodePerfDoc.html", null ],
    [ "OpCodeProfileEntry", "structOpCodeProfileEntry.html", null ],
    [ "OpCodeProfileLibrary", "classOpCodeProfileLibrary.html", null ],
    [ "PanelCatalog", "classPanelCatalog.html", null ],
    [ "PanelCategory", "structPanelCategory.html", null ],
    [ "PanelEntry", "structPanelEntry.html", null ],
    [ "Parser", "classParser.html", null ],
    [ "Parser::BoolScope", "structParser_1_1BoolScope.html", null ],
    [ "Parser::DepthGuard", "structParser_1_1DepthGuard.html", null ],
    [ "Parser::YieldIdScope", "structParser_1_1YieldIdScope.html", null ],
    [ "PathResolutionRow", "structPathResolutionRow.html", null ],
    [ "PerformanceRaceLibrary", "classPerformanceRaceLibrary.html", null ],
    [ "PerformanceRacePanel::SingleRunResult", "structPerformanceRacePanel_1_1SingleRunResult.html", null ],
    [ "PerfSample", "structPerfSample.html", null ],
    [ "PipelineRunner::PipelineResult", "structPipelineRunner_1_1PipelineResult.html", null ],
    [ "PrescanCheckRow", "structPrescanCheckRow.html", null ],
    [ "ProfileBarChart::Bar", "structProfileBarChart_1_1Bar.html", null ],
    [ "ProfileDashboardPanel::BackendTiming", "structProfileDashboardPanel_1_1BackendTiming.html", null ],
    [ "ProfileLibrary", "classProfileLibrary.html", null ],
    [ "ProfileScenario", "structProfileScenario.html", null ],
    [ "QDialog", "classQDialog.html", [
      [ "WelcomeWizard", "classWelcomeWizard.html", null ],
      [ "minilang::gui::CrashReportDialog", "classminilang_1_1gui_1_1CrashReportDialog.html", null ]
    ] ],
    [ "QFrame", "classQFrame.html", [
      [ "ActivityBar", "classActivityBar.html", null ]
    ] ],
    [ "QGraphicsView", "classQGraphicsView.html", [
      [ "AstViewer", "classAstViewer.html", null ]
    ] ],
    [ "QMainWindow", "classQMainWindow.html", [
      [ "Ide", "classIde.html", null ]
    ] ],
    [ "QObject", "classQObject.html", [
      [ "DebugController", "classDebugController.html", null ],
      [ "DebugCoordinator", "classDebugCoordinator.html", null ],
      [ "GuidedTour", "classGuidedTour.html", null ],
      [ "IdeController", "classIdeController.html", null ],
      [ "InterpreterWorker", "classInterpreterWorker.html", null ],
      [ "PipelineRunner", "classPipelineRunner.html", null ],
      [ "VmStepper", "classVmStepper.html", null ],
      [ "WorkerManager", "classWorkerManager.html", null ]
    ] ],
    [ "QPlainTextEdit", "classQPlainTextEdit.html", [
      [ "CodeEditor", "classCodeEditor.html", null ]
    ] ],
    [ "QStyledItemDelegate", "classQStyledItemDelegate.html", [
      [ "RichTextItemDelegate", "classRichTextItemDelegate.html", null ]
    ] ],
    [ "QSyntaxHighlighter", "classQSyntaxHighlighter.html", [
      [ "SyntaxHighlighter", "classSyntaxHighlighter.html", null ]
    ] ],
    [ "QWidget", "classQWidget.html", [
      [ "AstBuilderToyPanel", "classAstBuilderToyPanel.html", null ],
      [ "AstVisualizerPanel", "classAstVisualizerPanel.html", null ],
      [ "BackendComparePanel", "classBackendComparePanel.html", null ],
      [ "BackendParallelPanel", "classBackendParallelPanel.html", null ],
      [ "BugHuntPanel", "classBugHuntPanel.html", null ],
      [ "BytecodeTracePanel", "classBytecodeTracePanel.html", null ],
      [ "CallStackPanel", "classCallStackPanel.html", null ],
      [ "ClosureInspectorPanel", "classClosureInspectorPanel.html", null ],
      [ "CoroutineVisualizerPanel", "classCoroutineVisualizerPanel.html", null ],
      [ "CourseSystemPanel", "classCourseSystemPanel.html", null ],
      [ "EscapeAnalysisPanel", "classEscapeAnalysisPanel.html", null ],
      [ "ExceptionFlowPanel", "classExceptionFlowPanel.html", null ],
      [ "ExecutionTimelinePanel", "classExecutionTimelinePanel.html", null ],
      [ "ExerciseGraderPanel", "classExerciseGraderPanel.html", null ],
      [ "FindReplacePanel", "classFindReplacePanel.html", null ],
      [ "FuzzPlaygroundPanel", "classFuzzPlaygroundPanel.html", null ],
      [ "GcVisualizerPanel", "classGcVisualizerPanel.html", null ],
      [ "GlossaryPanel", "classGlossaryPanel.html", null ],
      [ "InlineCachePanel", "classInlineCachePanel.html", null ],
      [ "IrViewer", "classIrViewer.html", null ],
      [ "JitVisualizerPanel", "classJitVisualizerPanel.html", null ],
      [ "LabManualPanel", "classLabManualPanel.html", null ],
      [ "LearningPathPanel", "classLearningPathPanel.html", null ],
      [ "LineNumberArea", "classLineNumberArea.html", null ],
      [ "LintExplorerPanel", "classLintExplorerPanel.html", null ],
      [ "LoopUnrollingPanel", "classLoopUnrollingPanel.html", null ],
      [ "MemoryLayoutPanel", "classMemoryLayoutPanel.html", null ],
      [ "MemoryModelPanel", "classMemoryModelPanel.html", null ],
      [ "ModuleSystemVisualizerPanel", "classModuleSystemVisualizerPanel.html", null ],
      [ "PerformanceRacePanel", "classPerformanceRacePanel.html", null ],
      [ "PipelineViewer", "classPipelineViewer.html", null ],
      [ "ProfileBarChart", "classProfileBarChart.html", null ],
      [ "ProfileDashboardPanel", "classProfileDashboardPanel.html", null ],
      [ "RegisterAllocatorPanel", "classRegisterAllocatorPanel.html", null ],
      [ "ReplPanel", "classReplPanel.html", null ],
      [ "ReverseDebugTimelinePanel", "classReverseDebugTimelinePanel.html", null ],
      [ "StepExplainerPanel", "classStepExplainerPanel.html", null ],
      [ "SyntaxExplorerPanel", "classSyntaxExplorerPanel.html", null ],
      [ "TeachingPanelBase", "classTeachingPanelBase.html", [
        [ "BreakpointConditionPanel", "classBreakpointConditionPanel.html", null ],
        [ "CodeJourneyInfoPanel", "classCodeJourneyInfoPanel.html", null ],
        [ "DebugPanel", "classDebugPanel.html", null ],
        [ "IRTransformPanel", "classIRTransformPanel.html", null ],
        [ "WatchPanel", "classWatchPanel.html", null ],
        [ "WatchpointPanel", "classWatchpointPanel.html", null ]
      ] ],
      [ "TeachingPanelHeader", "classTeachingPanelHeader.html", null ],
      [ "TeachingSubPageBar", "classTeachingSubPageBar.html", null ],
      [ "TeachingTreePanel", "classTeachingTreePanel.html", null ],
      [ "TokenPuzzlePanel", "classTokenPuzzlePanel.html", null ],
      [ "VariableInspectorPanel", "classVariableInspectorPanel.html", null ],
      [ "VmStackPanel", "classVmStackPanel.html", null ],
      [ "VmStackSandboxPanel", "classVmStackSandboxPanel.html", null ]
    ] ],
    [ "RefCounted", "structRefCounted.html", [
      [ "Value::ArrayData", "structValue_1_1ArrayData.html", null ],
      [ "Value::BoxedIntData", "structValue_1_1BoxedIntData.html", null ],
      [ "Value::ChannelData", "structValue_1_1ChannelData.html", null ],
      [ "Value::ClosureData", "structValue_1_1ClosureData.html", null ],
      [ "Value::CoroutineData", "structValue_1_1CoroutineData.html", null ],
      [ "Value::DictData", "structValue_1_1DictData.html", null ],
      [ "Value::EnumVariantData", "structValue_1_1EnumVariantData.html", null ],
      [ "Value::InstanceData", "structValue_1_1InstanceData.html", null ],
      [ "Value::MutexData", "structValue_1_1MutexData.html", null ],
      [ "Value::RwLockData", "structValue_1_1RwLockData.html", null ],
      [ "Value::StringData", "structValue_1_1StringData.html", null ],
      [ "Value::ThreadData", "structValue_1_1ThreadData.html", null ],
      [ "Value::TupleData", "structValue_1_1TupleData.html", null ]
    ] ],
    [ "RefCountScenario", "structRefCountScenario.html", null ],
    [ "RefCountStep", "structRefCountStep.html", null ],
    [ "RegAllocAlgoInfo", "structRegAllocAlgoInfo.html", null ],
    [ "RegAllocScenario", "structRegAllocScenario.html", null ],
    [ "RegBytecodeChunk", "structRegBytecodeChunk.html", null ],
    [ "RegBytecodeChunk::SlotNameRange", "structRegBytecodeChunk_1_1SlotNameRange.html", null ],
    [ "RegCallFrame", "structRegCallFrame.html", null ],
    [ "RegisterAllocatorLibrary", "classRegisterAllocatorLibrary.html", null ],
    [ "RegisterBytecodeBackend::PendingJump", "structRegisterBytecodeBackend_1_1PendingJump.html", null ],
    [ "RegisterCompileResult", "structRegisterCompileResult.html", null ],
    [ "RegisterVM::OpenUpvalueEntry", "structRegisterVM_1_1OpenUpvalueEntry.html", null ],
    [ "RegisterVM::PendingJump", "structRegisterVM_1_1PendingJump.html", null ],
    [ "RegisterVM::RegClassInfo", "structRegisterVM_1_1RegClassInfo.html", null ],
    [ "RegisterVM::RegTryHandler", "structRegisterVM_1_1RegTryHandler.html", null ],
    [ "RegOpInfo", "structRegOpInfo.html", null ],
    [ "RegVMStepInfo", "structRegVMStepInfo.html", null ],
    [ "Result< T >", "classResult.html", null ],
    [ "ReverseDebugTimelinePanel::TimelineEntry", "structReverseDebugTimelinePanel_1_1TimelineEntry.html", null ],
    [ "RuntimeLimits::RuntimeConfig", "classRuntimeLimits_1_1RuntimeConfig.html", null ],
    [ "SandboxLevel", "structSandboxLevel.html", null ],
    [ "SandboxLibrary", "classSandboxLibrary.html", null ],
    [ "SandboxOp", "structSandboxOp.html", null ],
    [ "SmallArgs< T, N >", "classSmallArgs.html", null ],
    [ "SmallMap< K, V, N >", "classSmallMap.html", null ],
    [ "SmallMap< K, V, N >::const_iterator", "classSmallMap_1_1const__iterator.html", null ],
    [ "SmallMap< K, V, N >::iterator", "classSmallMap_1_1iterator.html", null ],
    [ "std::enable_shared_from_this", null, [
      [ "ASTNode", "classASTNode.html", [
        [ "ArrayLiteral", "classArrayLiteral.html", null ],
        [ "Assignment", "classAssignment.html", null ],
        [ "AwaitExpr", "classAwaitExpr.html", null ],
        [ "BinaryOp", "classBinaryOp.html", null ],
        [ "Block", "classBlock.html", null ],
        [ "BoolLiteral", "classBoolLiteral.html", null ],
        [ "BreakStmt", "classBreakStmt.html", null ],
        [ "ClassDecl", "classClassDecl.html", null ],
        [ "ContinueStmt", "classContinueStmt.html", null ],
        [ "DestructureBinding", "classDestructureBinding.html", null ],
        [ "DictLiteral", "classDictLiteral.html", null ],
        [ "EnumDecl", "classEnumDecl.html", null ],
        [ "EnumVariantExpr", "classEnumVariantExpr.html", null ],
        [ "ExportStmt", "classExportStmt.html", null ],
        [ "ForStmt", "classForStmt.html", null ],
        [ "FunCall", "classFunCall.html", null ],
        [ "FunDecl", "classFunDecl.html", null ],
        [ "IfStmt", "classIfStmt.html", null ],
        [ "ImportStmt", "classImportStmt.html", null ],
        [ "IndexAccess", "classIndexAccess.html", null ],
        [ "IndexAssign", "classIndexAssign.html", null ],
        [ "InterpolatedString", "classInterpolatedString.html", null ],
        [ "MacroCallExpr", "classMacroCallExpr.html", null ],
        [ "MacroDecl", "classMacroDecl.html", null ],
        [ "MatchExpr", "classMatchExpr.html", null ],
        [ "MatchPattern", "classMatchPattern.html", null ],
        [ "MemberAccess", "classMemberAccess.html", null ],
        [ "MemberAssign", "classMemberAssign.html", null ],
        [ "MethodCall", "classMethodCall.html", null ],
        [ "NullLiteral", "classNullLiteral.html", null ],
        [ "NumberLiteral", "classNumberLiteral.html", null ],
        [ "PrintStmt", "classPrintStmt.html", null ],
        [ "ReturnStmt", "classReturnStmt.html", null ],
        [ "StringLiteral", "classStringLiteral.html", null ],
        [ "SuperExpr", "classSuperExpr.html", null ],
        [ "ThrowStmt", "classThrowStmt.html", null ],
        [ "TraitDecl", "classTraitDecl.html", null ],
        [ "TryStmt", "classTryStmt.html", null ],
        [ "TupleLiteral", "classTupleLiteral.html", null ],
        [ "UnaryOp", "classUnaryOp.html", null ],
        [ "VarDecl", "classVarDecl.html", null ],
        [ "VarRef", "classVarRef.html", null ],
        [ "WhileStmt", "classWhileStmt.html", null ],
        [ "YieldExpr", "classYieldExpr.html", null ]
      ] ],
      [ "Environment", "classEnvironment.html", null ]
    ] ],
    [ "std::exception", null, [
      [ "DebugStopException", "classDebugStopException.html", null ],
      [ "std::runtime_error", null, [
        [ "BreakException", "classBreakException.html", null ],
        [ "ContinueException", "classContinueException.html", null ],
        [ "ParseError", "classParseError.html", null ],
        [ "ReturnException", "classReturnException.html", null ],
        [ "RuntimeError", "classRuntimeError.html", null ],
        [ "TailCallSignal", "classTailCallSignal.html", null ],
        [ "ThrowException", "classThrowException.html", null ],
        [ "YieldSignal", "classYieldSignal.html", null ]
      ] ]
    ] ],
    [ "StepExplainerLibrary", "classStepExplainerLibrary.html", null ],
    [ "StepExplainerPanel::StepInfo", "structStepExplainerPanel_1_1StepInfo.html", null ],
    [ "StepOpCodeDocEntry", "structStepOpCodeDocEntry.html", null ],
    [ "StringIntern", "classStringIntern.html", null ],
    [ "SyntaxProduction", "structSyntaxProduction.html", null ],
    [ "SyntaxProductionLibrary", "classSyntaxProductionLibrary.html", null ],
    [ "TCO::TailCallInfo", "structTCO_1_1TailCallInfo.html", null ],
    [ "TeachingPanelHeader::HelpDocView", "structTeachingPanelHeader_1_1HelpDocView.html", null ],
    [ "TestCase", "structTestCase.html", null ],
    [ "TierScenario", "structTierScenario.html", null ],
    [ "Token", "structToken.html", null ],
    [ "TokenPuzzleLevel", "structTokenPuzzleLevel.html", null ],
    [ "TokenPuzzleLibrary", "classTokenPuzzleLibrary.html", null ],
    [ "TraceSnapshot", "structTraceSnapshot.html", null ],
    [ "TransparentToolButton", "classTransparentToolButton.html", [
      [ "CleanToolButton", "classCleanToolButton.html", null ]
    ] ],
    [ "TypeFeedbackScenario", "structTypeFeedbackScenario.html", null ],
    [ "UnrollCompareRow", "structUnrollCompareRow.html", null ],
    [ "UnrollSimResult", "structUnrollSimResult.html", null ],
    [ "UpvalueDesc", "structUpvalueDesc.html", null ],
    [ "UpvaluePhaseDoc", "structUpvaluePhaseDoc.html", null ],
    [ "UpvaluePhaseLibrary", "classUpvaluePhaseLibrary.html", null ],
    [ "UpvalueStateInfo", "structUpvalueStateInfo.html", null ],
    [ "Value", "structValue.html", null ],
    [ "Value::ChannelInner", "structValue_1_1ChannelInner.html", null ],
    [ "Value::DictKeyEqual", "structValue_1_1DictKeyEqual.html", null ],
    [ "Value::DictKeyHash", "structValue_1_1DictKeyHash.html", null ],
    [ "Value::ThreadInner", "structValue_1_1ThreadInner.html", null ],
    [ "VarAllocInfo", "structVarAllocInfo.html", null ],
    [ "VariableInspectorLibrary", "classVariableInspectorLibrary.html", null ],
    [ "VariableSnapshot", "structVariableSnapshot.html", null ],
    [ "VariableTypeExample", "structVariableTypeExample.html", null ],
    [ "Visitor", "classVisitor.html", [
      [ "DefaultVisitor", "classDefaultVisitor.html", [
        [ "Compiler", "classCompiler.html", null ],
        [ "Formatter", "classFormatter.html", null ],
        [ "minilang::LiteralTypeWalker", "classminilang_1_1LiteralTypeWalker.html", null ]
      ] ],
      [ "Interpreter", "classInterpreter.html", null ]
    ] ],
    [ "VM::PendingJump", "structVM_1_1PendingJump.html", null ],
    [ "VM::TryHandler", "structVM_1_1TryHandler.html", null ],
    [ "VMCallFrame", "structVMCallFrame.html", null ],
    [ "VmCallStackEntry", "structVmCallStackEntry.html", null ],
    [ "VMClassInfo", "structVMClassInfo.html", null ],
    [ "VMClosureData", "structVMClosureData.html", null ],
    [ "VMEnumInfo", "structVMEnumInfo.html", null ],
    [ "VMEnumVariantInfo", "structVMEnumVariantInfo.html", null ],
    [ "VMStack", "classVMStack.html", null ],
    [ "VMStepInfo", "structVMStepInfo.html", null ],
    [ "VMUpvalue", "structVMUpvalue.html", null ],
    [ "VMYieldSignal", "structVMYieldSignal.html", null ],
    [ "WatchExpressionLibrary", "classWatchExpressionLibrary.html", null ],
    [ "WatchpointInfo", "structWatchpointInfo.html", null ],
    [ "WatchpointLibrary", "classWatchpointLibrary.html", null ],
    [ "WatchpointScenario", "structWatchpointScenario.html", null ],
    [ "WatchScenario", "structWatchScenario.html", null ],
    [ "WeakPoint", "structWeakPoint.html", null ],
    [ "WelcomeWizard::TokenSpan", "structWelcomeWizard_1_1TokenSpan.html", null ],
    [ "WorkerManager::QThreadDeleter", "structWorkerManager_1_1QThreadDeleter.html", null ],
    [ "WriteTarget", "structWriteTarget.html", null ]
];