#include "gui/LabManualPanel.h"

// ============================================================
// LabManualContent — 实验手册内容数据
// ------------------------------------------------------------
// 8 个实验章节，每章对应一个核心教学主题，从项目特性出发设计。
// Markdown 内容通过 QTextBrowser 渲染（Qt 内置子集）。
// ============================================================

const std::vector<LabChapter>& LabManualContent::chapters() {
    static const std::vector<LabChapter> kChapters = {
        LabChapter{
            "lab-01", "实验 1：词法分析 — 从字符到 Token",
            "# 实验 1：词法分析 — 从字符到 Token\n\n"
            "## 🏃 迷你实验（3 分钟）\n"
            "**目标**：感受\"源码被切成了有类型的片段\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：`var x = 1;`\n"
            "2. 打开\"编译管线可视化面板\"，切到 Token 步骤\n"
            "3. 数一数 Token 表中有几个 token\n"
            "4. 改成 `var x = 1; // 注释` 再看 token 数变化\n\n"
            "💡 源码被切成了有类型的片段——关键字 var / 标识符 x / 等号 = / 数字 1 / 分号 ;\n\n"
            "✅ **迷你实验验证**：你看到 5 个主流 token 了吗？（注释不计入主流）\n\n"
            "---\n\n"
            "## 目标\n"
            "理解词法分析器的职责：将源代码字符串切分为有意义的 Token 序列，并分离注释。\n\n"
            "## 关键概念\n"
            "- **Token 类型**：关键字 / 标识符 / 字面量 / 运算符 / 分隔符\n"
            "- **注释分离**：MiniLang 将 TK_LINE_COMMENT/TK_BLOCK_COMMENT 从主流分离到 lexer.comments()，供 Formatter 保留注释\n"
            "- **列号计算**：按 UTF-8 码位计数（columnAt）\n"
            "- **DoS 防护**：MAX_SOURCE_SIZE / MAX_TOKEN_COUNT / MAX_INTERP_DEPTH\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入以下代码：\n"
            "```\nvar x = 42; // 行内注释\nprint(x);\n```\n"
            "2. 打开\"编译管线可视化面板\"，切到 Token 步骤\n"
            "3. 观察 Token 表：每行包含 type/lexeme/line/column 字段\n"
            "4. 验证：注释 token 不在主流中（在 lexer.comments() 中）\n\n"
            "## 验证断言\n"
            "- Token 表中应有 5 个主流 token：var / x / = / 42 / ;\n"
            "- print(x); 对应 4 个 token：print / ( / x / ) / ;\n"
            "- 注释 token 不计入主流\n\n"
            "## 进阶\n"
            "- 尝试输入非法字符（如 $）观察错误 token\n"
            "- 尝试输入多字节 UTF-8 字符（如 \"é\"）观察列号计数",
            "var x = 42; // 行内注释\nprint(x);"
        },
        LabChapter{
            "lab-02", "实验 2：递归下降解析 — 从 Token 到 AST",
            "# 实验 2：递归下降解析 — 从 Token 到 AST\n\n"
            "## 🏃 迷你实验（5 分钟）\n"
            "**目标**：感受\"括号改变树的结构\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：`print(1 + 2 * 3);`\n"
            "2. 打开\"编译管线可视化面板\"，切到 AST 步骤\n"
            "3. 观察 AST：* 节点在 + 节点的右子树（因为乘法优先）\n"
            "4. 改成 `print((1 + 2) * 3);` 再看 AST 结构\n\n"
            "💡 同样的数字和运算符，仅括号不同就导致完全不同的树结构！\n"
            "   - 第一种：+ 在根，* 在右子树 → 1 + (2*3) = 7\n"
            "   - 第二种：* 在根，+ 在左子树 → (1+2) * 3 = 9\n\n"
            "✅ **迷你实验验证**：两次运行结果分别是 7 和 9 吗？\n\n"
            "---\n\n"
            "## 目标\n"
            "理解 Parser 的工作方式：手写递归下降，按优先级链解析表达式。\n\n"
            "## 关键概念\n"
            "- **优先级链**：assignment → or_ → and_ → equality → comparison → term → factor → unary → call → primary\n"
            "- **错误恢复**：synchronize() 在出错后跳到下一个同步点（语句边界）继续解析\n"
            "- **深度防护**：MAX_PARSE_DEPTH / MAX_BLOCK_DEPTH 通过 DepthGuard RAII 守卫防止 C++ 栈溢出\n"
            "- **AST 节点**：33 个 NodeType，ASTNode 基类含 line/column/nodeType + accept(Visitor&)\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入：\n"
            "```\nvar x = 1 + 2 * 3;\n```\n"
            "2. 打开\"编译管线可视化面板\"，切到 AST 步骤\n"
            "3. 观察 AST 树形结构：BinaryOp(+) 左 VarDecl(=x), 右 BinaryOp(*) 左 2 右 3\n"
            "4. 验证：乘法比加法优先级高，* 节点在 + 节点的右侧子树\n\n"
            "## 验证断言\n"
            "- AST 根节点是 Block\n"
            "- 第一个子节点是 VarDecl\n"
            "- VarDecl 的 initializer 是 BinaryOp(+)\n"
            "- + 的右子节点是 BinaryOp(*)\n\n"
            "## 进阶\n"
            "- 修改为 `var x = (1 + 2) * 3;` 观察括号如何改变 AST 结构\n"
            "- 输入语法错误（如 `var = ;`）观察错误恢复",
            "var x = 1 + 2 * 3;\nprint(x);"
        },
        LabChapter{
            "lab-03", "实验 3：树遍历解释器 — Visitor 模式执行 AST",
            "# 实验 3：树遍历解释器 — Visitor 模式执行 AST\n\n"
            "## 🏃 迷你实验（5 分钟）\n"
            "**目标**：感受\"解释器 = 递归遍历 + 执行\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：`print(42);`\n"
            "2. 点击运行 → 看到 `42`\n"
            "3. 打开 AST 面板 → 看到 `Print → NumberLiteral(42)`\n"
            "4. 改成 `print(3 + 4);` → 看 AST 变成 `Print → BinaryOp(+, 3, 4)`\n"
            "5. 运行 → 看到 `7`\n\n"
            "💡 这就是解释器的全部工作：遍历 AST，遇到 Print 就打印，遇到 BinaryOp 就计算！\n\n"
            "✅ **迷你实验验证**：你看到了 7 吗？\n\n"
            "---\n\n"
            "## 目标\n"
            "理解解释器的执行模型：通过 Visitor 模式递归遍历 AST 节点求值。\n\n"
            "## 关键概念\n"
            "- **Visitor 模式**：每个 AST 节点类型对应一个 visit 方法\n"
            "- **Environment**：链式作用域，boundInstance_ 缓存优化\n"
            "- **DebugController**：断点 / 单步 / 条件求值 / 沙箱隔离\n"
            "- **REPL**：续行判断（未闭合 {/(/[/字符串/块注释/try 缺 catch）\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入：\n"
            "```\nfun fib(n) {\n    if (n < 2) return n;\n    return fib(n - 1) + fib(n - 2);\n}\nfor (var i = 0; i < 10; i = i + 1) {\n    print(fib(i));\n}\n```\n"
            "2. 点击\"调试\"按钮（F6），设置断点在 fib 函数体首行\n"
            "3. 单步进入 / 跳过 / 跳出，观察调用栈\n"
            "4. 设置条件断点 `n == 5`，验证只在 n=5 时暂停\n\n"
            "## 验证断言\n"
            "- fib(0)=0, fib(1)=1, fib(2)=1, ..., fib(10)=55\n"
            "- 调用栈顶帧行号显示当前执行行（BUG-DBG-1 修复后）\n"
            "- 条件断点求值不污染程序状态（沙箱保存/恢复所有可变状态）\n\n"
            "## 进阶\n"
            "- 尝试 3 层嵌套闭包（参见 BUG-UV-1）\n"
            "- 在 REPL 中输入多行代码观察续行判断",
            "fun fib(n) {\n    if (n < 2) return n;\n    return fib(n - 1) + fib(n - 2);\n}\nfor (var i = 0; i < 10; i = i + 1) {\n    print(fib(i));\n}"
        },
        LabChapter{
            "lab-04", "实验 4：栈式字节码 VM — 编译与执行",
            "# 实验 4：栈式字节码 VM — 编译与执行\n\n"
            "## 🏃 迷你实验（5 分钟）\n"
            "**目标**：感受\"每条指令操作栈顶\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：`print(1 + 2);`\n"
            "2. 打开\"字节码轨迹面板\"，看到 3 条核心指令：\n"
            "   - `OP_INT 1`（压入 1）\n"
            "   - `OP_INT 2`（压入 2）\n"
            "   - `OP_ADD`（弹出两个，相加，压回 3）\n"
            "   - `OP_PRINT`（弹出并打印）\n"
            "3. 点击\"单步\"按钮，观察栈如何变化\n\n"
            "💡 栈式 VM 就是 push 和 pop 的游戏——每条指令操作栈顶！\n\n"
            "✅ **迷你实验验证**：单步到 OP_ADD 后，栈顶是否变成 3？\n\n"
            "---\n\n"
            "## 目标\n"
            "理解字节码编译与栈式 VM 执行：AST → BytecodeChunk → VM。\n\n"
            "## 关键概念\n"
            "- **OpCode**：~60 个栈式操作码（OP_CONSTANT/OP_ADD/OP_CALL 等）\n"
            "- **操作数栈**：定长 Value[1024]，push/pop 模型\n"
            "- **BytecodeChunk**：code（字节流）+ constants（常量池）+ lines（行号映射）\n"
            "- **常量池去重**：类型严格匹配 + 数值相等（BUG-CP-1 修复后）\n"
            "- **全局槽位**：编译期分配，运行时通过 slot 索引访问\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入：\n"
            "```\nvar x = 1 + 2;\nprint(x);\n```\n"
            "2. 打开\"编译管线可视化面板\"，切到字节码步骤\n"
            "3. 观察反汇编：\n"
            "   - OP_INT 1\n"
            "   - OP_INT 2\n"
            "   - OP_ADD\n"
            "   - OP_DEFINE_VAR 0\n"
            "   - OP_GET_VAR 0\n"
            "   - OP_PRINT\n"
            "4. 切换到 VM 模式，单步执行观察栈变化\n\n"
            "## 验证断言\n"
            "- 编译后字节码长度合理（约 6-8 字节）\n"
            "- 常量池去重：相同字面量共享索引\n"
            "- 栈式 VM 执行后 x == 3\n\n"
            "## 进阶\n"
            "- 尝试嵌套左值 `a[0][1] = x;` 观察栈平衡（参见 BUG-CP-2）\n"
            "- 启用 IR 路径观察字节码差异",
            "var x = 1 + 2;\nprint(x);"
        },
        LabChapter{
            "lab-05", "实验 5：寄存器式 VM — 三地址码与 IR",
            "# 实验 5：寄存器式 VM — 三地址码与 IR\n\n"
            "## 🏃 迷你实验（5 分钟）\n"
            "**目标**：感受\"不同后端的指令集不同\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：`print(1 + 2);`（与实验 4 相同的代码）\n"
            "2. 打开\"三后端对比面板\"，点击运行\n"
            "3. 对比 StackVM 与 RegisterVM 的字节码：\n"
            "   - StackVM：`OP_INT 1 / OP_INT 2 / OP_ADD / OP_PRINT`（栈式）\n"
            "   - RegisterVM：`LOAD_CONST r1, 1 / LOAD_CONST r2, 2 / ADD r1, r1, r2 / PRINT r1`（三地址码）\n\n"
            "💡 同样的代码，不同后端用完全不同的指令集表达！\n\n"
            "✅ **迷你实验验证**：两个后端的输出都是 3 吗？\n\n"
            "---\n\n"
            "## 目标\n"
            "理解 IR 中间表示与寄存器式 VM：AST → IR → RegBytecode → RegisterVM。\n\n"
            "## 关键概念\n"
            "- **IROp**：52 个 IR 指令（LOAD_CONST/ADD/CALL 等）\n"
            "- **虚拟寄存器**：SSA-like，nextVReg 分配\n"
            "- **RegOp**：~50 个三地址码操作码\n"
            "- **32 虚拟寄存器**：R0-R31，零堆分配（std::array<Value, 32>）\n"
            "- **优化 pass**：常量折叠 / 死代码消除 / 复制传播\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入：\n"
            "```\nvar x = 1 + 2;\nvar y = x * 3;\nprint(y);\n```\n"
            "2. 切换到 RegisterVM 模式（视图菜单）\n"
            "3. 打开\"编译管线可视化面板\"，切到 IR 步骤\n"
            "4. 观察 IR 指令：\n"
            "   - v0 = LOAD_CONST 1\n"
            "   - v1 = LOAD_CONST 2\n"
            "   - v2 = ADD v0, v1\n"
            "   - v3 = LOAD_CONST 3\n"
            "   - v4 = MUL v2, v3\n"
            "5. 启用优化观察 v2 是否被常量折叠\n\n"
            "## 验证断言\n"
            "- IR 中应看到 vreg 分配与三地址码结构\n"
            "- 寄存器 VM 执行后 y == 9\n"
            "- 优化启用后 IR 指令数减少\n\n"
            "## 进阶\n"
            "- 启用复制传播观察 v0/v1 是否被消除\n"
            "- 尝试死代码（如 `var unused = 5;`）观察 DCE 效果",
            "var x = 1 + 2;\nvar y = x * 3;\nprint(y);"
        },
        LabChapter{
            "lab-06", "实验 6：三后端一致性 — 语义等价验证",
            "# 实验 6：三后端一致性 — 语义等价验证\n\n"
            "## 🏃 迷你实验（3 分钟）\n"
            "**目标**：感受\"三条路径结果一致\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：`print(7 / 2);`\n"
            "2. 打开\"三后端对比面板\"，点击运行\n"
            "3. 查看 Interpreter / StackVM / RegisterVM 三个输出\n\n"
            "💡 三条路径都输出 `3`（整数除法截断向零，三后端统一）\n\n"
            "✅ **迷你实验验证**：三个后端的输出都是 3 吗？\n\n"
            "---\n\n"
            "## 目标\n"
            "理解三后端一致性约束：同一 MiniLang 源码在 Interpreter / StackVM / RegisterVM 三条路径上必须产生相同语义结果。\n\n"
            "## 关键概念\n"
            "- **三后端一致性**：整数除法截断向零 / and-or 短路返回原值 / 类型注解强制 / super 调用语义\n"
            "- **ConsistencyDiff 测试**：190 个差分测试用例验证三后端等价\n"
            "- **已知差异**：非方法上下文 super 错误消息文本不同（错误类型相同，行为一致）\n"
            "- **错误消息归一化**：差分时归一化错误类型而非文本\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入：\n"
            "```\nprint(7 / 2);\nprint(7.0 / 2);\nprint(0 or \"default\");\nprint(5 and 0);\n```\n"
            "2. 打开\"三后端并行对比面板\"\n"
            "3. 点击\"运行对比\"按钮\n"
            "4. 观察三列输出是否一致\n\n"
            "## 验证断言\n"
            "- 三后端都输出：3 / 3.5 / 0 / 0\n"
            "- 整数除法 7/2 三后端一致为 3\n"
            "- 浮点除法 7.0/2 三后端一致为 3.5\n"
            "- and/or 短路返回操作数原值（非布尔）\n\n"
            "## 进阶\n"
            "- 尝试触发已知差异（非方法上下文 super）观察错误消息差异\n"
            "- 修改源码观察哪些情况下三后端可能不一致（如默认参数表达式）",
            "print(7 / 2);\nprint(7.0 / 2);\nprint(0 or \"default\");\nprint(5 and 0);"
        },
        LabChapter{
            "lab-07", "实验 7：内存模型 — NaN-boxing 与 COW",
            "# 实验 7：内存模型 — NaN-boxing 与 COW\n\n"
            "## 🏃 迷你实验（5 分钟）\n"
            "**目标**：感受\"写时复制真正复制了\"\n\n"
            "**步骤**：\n"
            "1. 在编辑器中输入：\n"
            "```\nvar a = [1, 2, 3];\nvar b = a;\nb[0] = 99;\nprint(a[0]);\nprint(b[0]);\n```\n"
            "2. 运行 → 看到 `1` 和 `99`\n"
            "3. 打开\"内存模型面板\"，观察 ArrayData 的引用计数和 COW detach 时机\n\n"
            "💡 a 和 b 最初共享同一个 ArrayData（refCount=2）；b[0]=99 触发 COW detach，b 拷贝出新的 ArrayData，从此 a 和 b 独立\n\n"
            "✅ **迷你实验验证**：a[0] 是 1，b[0] 是 99 吗？（写时复制真正复制了）\n\n"
            "---\n\n"
            "## 目标\n"
            "理解 MiniLang 的内存模型：Value 8 字节 NaN-boxing，堆类型侵入式 RefCounted，数组/字典 Copy-On-Write。\n\n"
            "## 关键概念\n"
            "- **NaN-boxing**：8 字节 Value，tag bits / payload 分段编码\n"
            "- **int48 内联存储**：int 在 int48 范围内联存储，超范围自动装箱\n"
            "- **RefCounted**：侵入式引用计数基类，数组/字典/字符串/InstanceData 都继承\n"
            "- **COW**：写前检查独占所有权，refCount > 1 时复制\n"
            "- **GcManager sweep**：周期性清理 refCount==0 的对象防 UAF\n\n"
            "## 实验步骤\n"
            "1. 在编辑器中输入：\n"
            "```\nvar a = [1, 2, 3];\nvar b = a;          // 共享所有权\nb.push(4);          // COW 触发，b 拥有新副本\nprint(a.len());     // 3\nprint(b.len());     // 4\n```\n"
            "2. 运行观察输出\n"
            "3. 修改为 `var b = a; b[0] = 99;` 验证 COW 写时复制\n"
            "4. 测试大数组传递观察引用计数（暂无可视化，需通过性能感知）\n\n"
            "## 验证断言\n"
            "- a 与 b 共享同一 ArrayData 直到第一次写\n"
            "- 任何修改 b 的操作触发 COW，a 不受影响\n"
            "- 字符串拼接（+）任一操作数为字符串即触发\n\n"
            "## 进阶\n"
            "- 尝试嵌套数组 `[[1,2],[3,4]]` 观察深拷贝 vs 浅拷贝\n"
            "- 测试字符串索引 UTF-8 多字节字符（参见 BUG-INTP-3）",
            "var a = [1, 2, 3];\nvar b = a;\nb.push(4);\nprint(a.len());\nprint(b.len());"
        },
        LabChapter{
            "lab-08", "实验 8：Bug 狩猎 — 从历史 Bug 学习",
            "# 实验 8：Bug 狩猎 — 从历史 Bug 学习\n\n"
            "## 🏃 迷你实验（5 分钟）\n"
            "**目标**：感受\"Bug 隐藏在细节中\"\n\n"
            "**步骤**：\n"
            "1. 打开\"Bug 狩猎面板\"\n"
            "2. 选择难度筛选中的\"入门级\"\n"
            "3. 选一道入门级题目（如 BUG-READ-03 格式化预测）\n"
            "4. 不看提示，先自己预测代码运行结果\n"
            "5. 点击\"运行\"对比期望行为\n\n"
            "💡 入门级题目不需要看代码，重点是培养 Debug 直觉——预测→对比→理解差异\n\n"
            "✅ **迷你实验验证**：你的预测与实际行为一致吗？\n\n"
            "---\n\n"
            "## 目标\n"
            "通过项目自身沉淀的真实 Bug 训练调试能力：阅读代码、预测行为、定位根因。\n\n"
            "## 关键概念\n"
            "- **高频 Bug 模式**：栈不平衡 / UAF / 泄漏 / 语义不一致 / 竞态 / 错误传播 / 边界条件\n"
            "- **三后端对称性审计**：修改某后端时同步检查其他两个后端\n"
            "- **错误路径栈平衡**：每个 error return 点必须 popN 清理栈\n"
            "- **RAII guard 构造顺序**：必须在状态修改前构造以捕获正确的 saved 状态\n\n"
            "## 实验步骤\n"
            "1. 打开\"Bug 狩猎\"面板\n"
            "2. 选择 BUG-CP-1（常量池去重陷阱）\n"
            "3. 阅读背景：int(0) 与 float(0.0) 共享常量索引的后果\n"
            "4. 在内嵌编辑器中预测输出\n"
            "5. 点击\"运行验证\"查看实际输出\n"
            "6. 逐步查看提示，最后查看答案\n"
            "7. 重复 5-10 道题，覆盖不同 Bug 模式\n\n"
            "## 验证断言\n"
            "- 能区分 Value::equals()（数值相等）与类型严格相等\n"
            "- 理解三后端对称性约束：修改指令布局时必须同步更新 instructionSizeAt\n"
            "- 能识别\"push 在检查之前\"反模式\n"
            "- 理解条件断点沙箱必须保存/恢复所有可变状态\n\n"
            "## 进阶\n"
            "- 完成 10 道题后尝试在主编辑器中重现某个 Bug\n"
            "- 阅读 project_memory.md 中的\"Lessons Learned\"加深理解",
            "var a = 7 / 2;\nvar b = 7.0 / 2;\nprint(a);\nprint(b);"
        }
    };
    return kChapters;
}
